version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html


