version: '3'

networks:
  demo:
    driver: overlay

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - php
    networks:
      - demo

  php:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    image: localhost:5000/myphp:1
#    volumes:
#      - ./app:/var/www/html
    links:
      - db
      - logdb
      - scribe
      - memcached
      - redis
    networks:
      - demo

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - ./mysql/game:/docker-entrypoint-initdb.d
    networks:
      - demo

  logdb:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - ./mysql/log:/docker-entrypoint-initdb.d
    networks:
      - demo

  scribe:
    image: n0n0x/docker-scribe
    volumes:
      - ./scribe/scribe.conf:/etc/scribe.conf
      - ./scribe/log:/log
    networks:
      - demo

  memcached:
    image: memcached
    networks:
      - demo

  redis:
    image: redis
    networks:
      - demo

